[package]
name = "cargo-preflight"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_derive = "1.0.219"
confy = "0.6.1"
serde = "1.0.219"
cargo = "0.87.1"
anyhow = "1.0.98"
thiserror = "2.0.12"
clap = { version = "4.5.36", features = ["cargo", "derive"] }
clap-cargo = "0.15.2"
dirs = "6.0.0"
colored = "3.0.0"
