[package]
name = "cargo-preflight"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_derive = "1.0.219"
confy = "0.6.1"
serde = "1.0.219"
clap = { version = "4.5.36", features = ["derive"] }
cargo = "0.87.1"
thiserror = "2.0.12"
