[package]
name = "cargo-preflight"
version = "0.1.0"
edition = "2024"
authors = ["supinie <preflight@supinie.com>"]
description = "A custom Cargo subcommand to run local 'CI' on certain Git actions."
readme = "README.md"
repository = "https://github.com/supinie/cargo-preflight"
license = "MIT"
keywords = ["dev-tools", "testing", "CI", "git"]
categories = ["command-line-utilities", "development-tools", "development-tools::cargo-plugins", "development-tools::testing"]

[dependencies]
serde_derive = "1.0.219"
confy = "0.6.1"
serde = "1.0.219"
anyhow = "1.0.98"
thiserror = "2.0.12"
clap = { version = "4.5.36", features = ["cargo", "derive"] }
clap-cargo = "0.15.2"
dirs = "6.0.0"
colored = "3.0.0"
inquire = "0.7.5"
